apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-sync-service-account
  namespace: istio-system
  labels:
    app: cert-sync

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: cert-sync
  name: cert-sync-istio-system
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-sync-istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-sync-istio-system
subjects:
  - kind: ServiceAccount
    name: cert-sync-service-account
    namespace: istio-system

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cert-sync
  namespace: istio-system
  labels:
    app: cert-sync
spec:
  template:
    metadata:
      labels:
        app: cert-sync
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      serviceAccountName: cert-sync-service-account
      containers:
        - name: cert-sync
          image: "dunjut/cert-sync:0.1.0"
          imagePullPolicy: IfNotPresent
          args:
          - --certDir
          - /etc/istio/ingressgateway-certs
          volumeMounts:
          - name: certdir
            mountPath: "/etc/istio/ingressgateway-certs"
      volumes:
      - name: certdir
        hostPath:
          path: /tmp/ingressgateway-certs
